spring.application.name=app
# Database
spring.datasource.url=jdbc:mysql://localhost:3307/bank?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.servlet.multipart.max-file-size=15KB
spring.servlet.multipart.max-request-size=15KB

jwt.secret=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW5kdW5AZ21haWwuY29tIiwiaWQiOjIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzUzODU4MjU4LCJleHAiOjE3NTM4NjE4NTh9.9727Yye-n5jC-VGvsoFZORcOOaPK1AX8_ZMIT5DKlZg
jwt.expiration=3600000